teacher = list()
teacher_name = input('Teacher’s last name: ')
teacher_position = input('Position: ')
students_amount = input('Number of students in classes: ')
students_amount = students_amount.split(' ')
teacher.append(teacher_name)
teacher.append(teacher_position)
teacher.append(students_amount)
print(teacher)