who = input('Enter the name of your startup: ')
day = input('Enter the foundation date of the startup: ')
year = int(input("Enter the startup’s foundation year: "))
print('Welcome', who, '- a promising new IT startup.') 
print('The', who, 'company was founded on', day, year, '.')
